-- 코드를 입력하세요
SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, ROUND(IFNULL(b.SCORE, 0), 2) AS SCORE
FROM REST_INFO AS a
JOIN (SELECT REST_ID, AVG(REVIEW_SCORE) AS SCORE
      FROM REST_REVIEW
      GROUP BY(REST_ID)) AS b 
ON a.REST_ID = b.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY a.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;