-- 코드를 작성해주세요
SELECT a.ITEM_ID, a.ITEM_NAME, a.RARITY
FROM ITEM_INFO a
JOIN (SELECT DISTINCT t.ITEM_ID
    FROM ITEM_INFO i
    JOIN ITEM_TREE t
        ON i.ITEM_ID = t.PARENT_ITEM_ID
    WHERE RARITY = "RARE") b
ON a.ITEM_ID = b.ITEM_ID
ORDER BY a.ITEM_ID DESC;